package de.charite.compbio.ontolib.io.obo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.HeaderKeyValueContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueAutoGeneratedByContext;

public class Antlr4OBOParserTestStanzaEntryAutoGeneratedBy extends Antlr4OBOParserTestBase {

  @Test
  public void testParseNoModifierNoCommentAsTypedefKeyValue() {
    final String text = "auto-generated-by: ACME.exe\n";
    final Antlr4OBOParser parser = buildParser(text);
    final HeaderKeyValueContext ctx = parser.headerKeyValue();
    final StanzaEntry stanzaEntry = (StanzaEntry) getOuterListener().getValue(ctx);

    assertEquals(StanzaEntryType.AUTO_GENERATED_BY, stanzaEntry.getType());
    assertNull(stanzaEntry.getTrailingModifier());
    assertNull(stanzaEntry.getComment());
  }

  @Test
  public void testParseNoModifierNoCommentAsKeyValueAltID() {
    final String text = "auto-generated-by: ACME.exe\n";
    final Antlr4OBOParser parser = buildParser(text);
    final KeyValueAutoGeneratedByContext ctx = parser.keyValueAutoGeneratedBy();
    final StanzaEntryAutoGeneratedBy stanzaEntry =
        (StanzaEntryAutoGeneratedBy) getOuterListener().getValue(ctx);

    assertEquals(StanzaEntryType.AUTO_GENERATED_BY, stanzaEntry.getType());
    assertEquals("ACME.exe", stanzaEntry.getGenerator());
    assertNull(stanzaEntry.getTrailingModifier());
    assertNull(stanzaEntry.getComment());
  }

  @Test
  public void testParseModifierNoCommentAsKeyValueAltID() {
    final String text = "auto-generated-by: ACME.exe {key=value}\n";
    final Antlr4OBOParser parser = buildParser(text);
    final KeyValueAutoGeneratedByContext ctx = parser.keyValueAutoGeneratedBy();
    final StanzaEntryAutoGeneratedBy stanzaEntry =
        (StanzaEntryAutoGeneratedBy) getOuterListener().getValue(ctx);

    assertEquals(StanzaEntryType.AUTO_GENERATED_BY, stanzaEntry.getType());
    assertEquals("ACME.exe", stanzaEntry.getGenerator());
    assertEquals("TrailingModifier [keyValue=[KeyValue [key=key, value=value]]]",
        stanzaEntry.getTrailingModifier().toString());
    assertNull(stanzaEntry.getComment());
  }

  @Test
  public void testParseNoModifierCommentAsKeyValueAltID() {
    final String text = "auto-generated-by: ACME.exe ! comment\n";
    final Antlr4OBOParser parser = buildParser(text);
    final KeyValueAutoGeneratedByContext ctx = parser.keyValueAutoGeneratedBy();
    final StanzaEntryAutoGeneratedBy stanzaEntry =
        (StanzaEntryAutoGeneratedBy) getOuterListener().getValue(ctx);

    assertEquals(StanzaEntryType.AUTO_GENERATED_BY, stanzaEntry.getType());
    assertEquals("ACME.exe", stanzaEntry.getGenerator());
    assertNull(stanzaEntry.getTrailingModifier());
    assertEquals("comment", stanzaEntry.getComment().toString());
  }

  @Test
  public void testParseModifierCommentAsKeyValueAltID() {
    final String text = "auto-generated-by: ACME.exe {key=value} ! comment\n";
    final Antlr4OBOParser parser = buildParser(text);
    final KeyValueAutoGeneratedByContext ctx = parser.keyValueAutoGeneratedBy();
    final StanzaEntryAutoGeneratedBy stanzaEntry =
        (StanzaEntryAutoGeneratedBy) getOuterListener().getValue(ctx);

    assertEquals(StanzaEntryType.AUTO_GENERATED_BY, stanzaEntry.getType());
    assertEquals("ACME.exe", stanzaEntry.getGenerator());
    assertEquals("TrailingModifier [keyValue=[KeyValue [key=key, value=value]]]",
        stanzaEntry.getTrailingModifier().toString());
    assertEquals("comment", stanzaEntry.getComment());
  }

}
