package de.charite.compbio.ontolib.io.obo;

import java.util.ArrayList;
import java.util.List;

import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeProperty;
import org.antlr.v4.runtime.tree.TerminalNode;

import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.DbXRefContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.DbXRefListContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.EolComment2Context;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.InstanceStanzaKeyValueContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueAltIDContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueAutogeneratedByContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueCommentContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueConsiderContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueCreatedByContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueCreationDateContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueDataVersionContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueDateContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueDefContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueDefaultRelationshipIdPrefixContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueDisjointFromContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueDomainContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueFormatVersionContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueGenericContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIDContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIdMappingContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIdspaceContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueImportContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueInstanceOfContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIntersectionOfContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueInverseOfContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsAContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsAnonymousContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsAntisymmetricContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsCyclicContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsMetadataContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsObsoleteContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsReflexiveContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsSymmetricContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueIsTransitiveContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueNameContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueRangeContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueRelationshipContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueRemarkContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueReplacedByContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueSavedByContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueSubsetContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueSubsetdefContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueSynonymContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueSynonymTypedefContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueTransitiveOverContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueUnionOfContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.KeyValueXRefContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.StanzaContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.TermStanzaKeyValueContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.TrailingModifierContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.TrailingModifierKeyValueContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParser.TypedefStanzaKeyValueContext;
import de.charite.compbio.ontolib.io.obo.parser.Antlr4OBOParserBaseListener;

/**
 * Master <code>ParseTreeListener</code> to use for OBO parsing.
 *
 * @author <a href="mailto:manuel.holtgrewe@bihealth.de">Manuel Holtgrewe</a>
 */
public class Antlr4OBOParserListenerImpl extends Antlr4OBOParserBaseListener {

  /** maps nodes to Objects with Map<ParseTree,Object> */
  ParseTreeProperty<Object> values = new ParseTreeProperty<>();

  /**
   * Set associated <code>value</code> for the given {@link ParseTree} <code>node</code>.
   * 
   * @param node The {@link ParseTree} <code>node</code> to set the value for.
   * @param value The value to put for the given {@link ParseTree} <code>node</code>.
   */
  public void setValue(ParseTree node, Object value) {
    values.put(node, value);
  }

  /**
   * @param node The {@link ParseTree} node to get the value for.
   * @return The value associated with <code>node</code>.
   */
  public Object getValue(ParseTree node) {
    return values.get(node);
  }

  /** Current {@link StanzaType}. */
  private StanzaType stanzaType = null;

  /** List of current stanza's {@link StanzaEntry} objects. */
  private List<StanzaEntry> stanzaKeyValues = null;

  /**
   * Called on entering <code>stanza</code> rule.
   */
  @Override
  public void enterStanza(StanzaContext ctx) {
    // Create new list of key/value pairs
    stanzaKeyValues = new ArrayList<StanzaEntry>();

    // Extract and store current stanza type
    if (ctx.termStanza() != null) {
      stanzaType = StanzaType.TERM;
    } else if (ctx.typedefStanza() != null) {
      stanzaType = StanzaType.TYPEDEF;
    } else if (ctx.instanceStanza() != null) {
      stanzaType = StanzaType.INSTANCE;
    } else {
      throw new RuntimeException("Unexpected stanza type. This should not happen.");
    }
  }

  /**
   * Called on leaving <code>stanza</code> rule.
   */
  @Override
  public void exitStanza(StanzaContext ctx) {
    // Construct and store current Stanza object
    setValue(ctx, Stanza.create(stanzaType, stanzaKeyValues));

    // Zap list of key/value pairs
    stanzaKeyValues = null;
  }

  /**
   * Called on leaving <code>termKeyValue</code>, moves child <code>keyValue*</code> to this
   * {@link ParseTree}'s map entry.
   */
  @Override
  public void exitTermStanzaKeyValue(TermStanzaKeyValueContext ctx) {
    setValue(ctx, getValue(ctx.getChild(0)));
  }

  /**
   * Called on leaving <code>instanceKeyValue</code>, moves child <code>keyValue*</code> to this
   * {@link ParseTree}'s map entry.
   */
  @Override
  public void exitInstanceStanzaKeyValue(InstanceStanzaKeyValueContext ctx) {
    setValue(ctx, getValue(ctx.getChild(0)));
  }

  /**
   * Called on leaving <code>typedefKeyValue</code>, moves child <code>keyValue*</code> to this
   * {@link ParseTree}'s map entry.
   */
  @Override
  public void exitTypedefStanzaKeyValue(TypedefStanzaKeyValueContext ctx) {
    setValue(ctx, getValue(ctx.getChild(0)));
  }

  /** Called on entering <code>keyValueID</code> rule. */
  @Override
  public void enterKeyValueID(KeyValueIDContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueID(ctx);
  }

  /** Called on leaving <code>keyValueID</code> rule. */
  @Override
  public void exitKeyValueID(KeyValueIDContext ctx) {
    final String id = ctx.stringValue().getText();
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntryID(id, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueName</code> rule. */
  @Override
  public void enterKeyValueName(KeyValueNameContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueName(ctx);
  }

  /** Called on leaving <code>keyValueName</code> rule. */
  @Override
  public void exitKeyValueName(KeyValueNameContext ctx) {
    final String name = ctx.stringValue().getText();
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntryName(name, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueIsAnonymous</code> rule. */
  @Override
  public void enterKeyValueIsAnonymous(KeyValueIsAnonymousContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsAnonymous(ctx);
  }

  /** Called on leaving <code>keyValueIsAnonymous</code> rule. */
  @Override
  public void exitKeyValueIsAnonymous(KeyValueIsAnonymousContext ctx) {
    final boolean isAnonymous = ctx.BooleanValue().getText().equals("true");
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntryIsAnonymous(isAnonymous, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueIsAltID</code> rule. */
  @Override
  public void enterKeyValueAltID(KeyValueAltIDContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueAltID(ctx);
  }

  /** Called on leaving <code>keyValueIsAltID</code> rule. */
  @Override
  public void exitKeyValueAltID(KeyValueAltIDContext ctx) {
    final String altID = ctx.stringValue().getText();
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntryAltID(altID, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueDef</code> rule. */
  @Override
  public void enterKeyValueDef(KeyValueDefContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueDef(ctx);
  }

  /** Called on leaving <code>keyValueDef</code> rule. */
  @Override
  public void exitKeyValueDef(KeyValueDefContext ctx) {
    final String text = ctx.QuotedString().getText();
    final DBXRefList dbXRefList = (DBXRefList) getValue(ctx.dbXRefList());
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntryDef(text, dbXRefList, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueComment</code> rule. */
  @Override
  public void enterKeyValueComment(KeyValueCommentContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueComment(ctx);
  }

  /** Called on leaving <code>keyValueComment</code> rule. */
  @Override
  public void exitKeyValueComment(KeyValueCommentContext ctx) {
    final String text = ctx.stringValue().getText();
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntryComment(text, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueSubset</code> rule. */
  @Override
  public void enterKeyValueSubset(KeyValueSubsetContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueSubset(ctx);
  }

  /** Called on leaving <code>keyValueSubset</code> rule. */
  @Override
  public void exitKeyValueSubset(KeyValueSubsetContext ctx) {
    final String name = ctx.stringValue().getText();
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntrySubset(name, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueSynonym</code> rule. */
  @Override
  public void enterKeyValueSynonym(KeyValueSynonymContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueSynonym(ctx);
  }

  /** Called on leaving <code>keyValueSynonym</code> rule. */
  @Override
  public void exitKeyValueSynonym(KeyValueSynonymContext ctx) {
    final String text = ctx.QuotedString().getText();
    final SynonymScopeIdentifier synonymScopeIdentifier =
        SynonymScopeIdentifier.valueOf(ctx.ScopeIdentifier().getText());
    final String scopeTypeName = trimmedEmptyToNull(ctx.Word());
    final DBXRefList dbXRefList = (DBXRefList) getValue(ctx.dbXRefList());
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());
    final String comment = trimmedEmptyToNull(ctx.eolComment2());

    setValue(ctx, new StanzaEntrySynonym(text, synonymScopeIdentifier, scopeTypeName,
        dbXRefList, trailingModifier, comment));
  }

  /** Called on entering <code>keyValueXRef</code> rule. */
  @Override
  public void enterKeyValueXRef(KeyValueXRefContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueXRef(ctx);
  }

  /** Called on leaving <code>keyValueXRef</code> rule. */
  @Override
  public void exitKeyValueXRef(KeyValueXRefContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueXRef(ctx);
  }

  /** Called on entering <code>keyValueIsA</code> rule. */
  @Override
  public void enterKeyValueIsA(KeyValueIsAContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsA(ctx);
  }

  /** Called on leaving <code>keyValueIsA</code> rule. */
  @Override
  public void exitKeyValueIsA(KeyValueIsAContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsA(ctx);
  }

  /** Called on entering <code>keyValueIntersectionOf</code> rule. */
  @Override
  public void enterKeyValueIntersectionOf(KeyValueIntersectionOfContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIntersectionOf(ctx);
  }

  /** Called on leaving <code>keyValueIntersectionOf</code> rule. */
  @Override
  public void exitKeyValueIntersectionOf(KeyValueIntersectionOfContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIntersectionOf(ctx);
  }

  /** Called on entering <code>keyValueUnionOf</code> rule. */
  @Override
  public void enterKeyValueUnionOf(KeyValueUnionOfContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueUnionOf(ctx);
  }

  /** Called on leaving <code>keyValueUnionOf</code> rule. */
  @Override
  public void exitKeyValueUnionOf(KeyValueUnionOfContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueUnionOf(ctx);
  }

  /** Called on entering <code>keyValueDisjointFrom</code> rule. */
  @Override
  public void enterKeyValueDisjointFrom(KeyValueDisjointFromContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueDisjointFrom(ctx);
  }

  /** Called on leaving <code>keyValueDisjointFrom</code> rule. */
  @Override
  public void exitKeyValueDisjointFrom(KeyValueDisjointFromContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueDisjointFrom(ctx);
  }

  /** Called on entering <code>keyValueRelationship</code> rule. */
  @Override
  public void enterKeyValueRelationship(KeyValueRelationshipContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueRelationship(ctx);
  }

  /** Called on leaving <code>keyValueRelationship</code> rule. */
  @Override
  public void exitKeyValueRelationship(KeyValueRelationshipContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueRelationship(ctx);
  }

  /** Called on entering <code>keyValueIsObsolete</code> rule. */
  @Override
  public void enterKeyValueIsObsolete(KeyValueIsObsoleteContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsObsolete(ctx);
  }

  /** Called on leaving <code>keyValueIsObsolete</code> rule. */
  @Override
  public void exitKeyValueIsObsolete(KeyValueIsObsoleteContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsObsolete(ctx);
  }

  /** Called on entering <code>keyValueReplacedBy</code> rule. */
  @Override
  public void enterKeyValueReplacedBy(KeyValueReplacedByContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueReplacedBy(ctx);
  }

  /** Called on leaving <code>keyValueReplacedBy</code> rule. */
  @Override
  public void exitKeyValueReplacedBy(KeyValueReplacedByContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueReplacedBy(ctx);
  }

  /** Called on entering <code>keyValueConsider</code> rule. */
  @Override
  public void enterKeyValueConsider(KeyValueConsiderContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueConsider(ctx);
  }

  /** Called on leaving <code>keyValueConsider</code> rule. */
  @Override
  public void exitKeyValueConsider(KeyValueConsiderContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueConsider(ctx);
  }

  /** Called on entering <code>keyValueCreatedBy</code> rule. */
  @Override
  public void enterKeyValueCreatedBy(KeyValueCreatedByContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueCreatedBy(ctx);
  }

  /** Called on leaving <code>keyValueCreatedBy</code> rule. */
  @Override
  public void exitKeyValueCreatedBy(KeyValueCreatedByContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueCreatedBy(ctx);
  }

  /** Called on entering <code>keyValueCreationDate</code> rule. */
  @Override
  public void enterKeyValueCreationDate(KeyValueCreationDateContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueCreationDate(ctx);
  }

  /** Called on leaving <code>keyValueCreationDate</code> rule. */
  @Override
  public void exitKeyValueCreationDate(KeyValueCreationDateContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueCreationDate(ctx);
  }

  /** Called on entering <code>keyValueGeneric</code> rule. */
  @Override
  public void enterKeyValueGeneric(KeyValueGenericContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueGeneric(ctx);
  }

  /** Called on leaving <code>keyValueGeneric</code> rule. */
  @Override
  public void exitKeyValueGeneric(KeyValueGenericContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueGeneric(ctx);
  }

  /** Called on entering <code>keyValueDomain</code> rule. */
  @Override
  public void enterKeyValueDomain(KeyValueDomainContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueDomain(ctx);
  }

  /** Called on leaving <code>keyValueDomain</code> rule. */
  @Override
  public void exitKeyValueDomain(KeyValueDomainContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueDomain(ctx);
  }

  /** Called on entering <code>keyValueRange</code> rule. */
  @Override
  public void enterKeyValueRange(KeyValueRangeContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueRange(ctx);
  }

  /** Called on leaving <code>keyValueRange</code> rule. */
  @Override
  public void exitKeyValueRange(KeyValueRangeContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueRange(ctx);
  }

  /** Called on entering <code>keyValueInverseOf</code> rule. */
  @Override
  public void enterKeyValueInverseOf(KeyValueInverseOfContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueInverseOf(ctx);
  }

  /** Called on leaving <code>keyValueInverseOf</code> rule. */
  @Override
  public void exitKeyValueInverseOf(KeyValueInverseOfContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueInverseOf(ctx);
  }

  /** Called on entering <code>keyValueTransitiveOver</code> rule. */
  @Override
  public void enterKeyValueTransitiveOver(KeyValueTransitiveOverContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueTransitiveOver(ctx);
  }

  /** Called on leaving <code>keyValueTransitiveOver</code> rule. */
  @Override
  public void exitKeyValueTransitiveOver(KeyValueTransitiveOverContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueTransitiveOver(ctx);
  }

  /** Called on entering <code>keyValueIsCyclic</code> rule. */
  @Override
  public void enterKeyValueIsCyclic(KeyValueIsCyclicContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsCyclic(ctx);
  }

  /** Called on leaving <code>keyValueIsCyclic</code> rule. */
  @Override
  public void exitKeyValueIsCyclic(KeyValueIsCyclicContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsCyclic(ctx);
  }

  /** Called on entering <code>keyValueReflexive</code> rule. */
  @Override
  public void enterKeyValueIsReflexive(KeyValueIsReflexiveContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsReflexive(ctx);
  }

  /** Called on leaving <code>keyValueReflexive</code> rule. */
  @Override
  public void exitKeyValueIsReflexive(KeyValueIsReflexiveContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsReflexive(ctx);
  }

  /** Called on entering <code>keyValueIsSymmetric</code> rule. */
  @Override
  public void enterKeyValueIsSymmetric(KeyValueIsSymmetricContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsSymmetric(ctx);
  }

  /** Called on leaving <code>keyValueIsSymmetric</code> rule. */
  @Override
  public void exitKeyValueIsSymmetric(KeyValueIsSymmetricContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsSymmetric(ctx);
  }

  /** Called on entering <code>keyValueIsAntisymmetric</code> rule. */
  @Override
  public void enterKeyValueIsAntisymmetric(KeyValueIsAntisymmetricContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsAntisymmetric(ctx);
  }

  /** Called on leaving <code>keyValueIsAntisymmetric</code> rule. */
  @Override
  public void exitKeyValueIsAntisymmetric(KeyValueIsAntisymmetricContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsAntisymmetric(ctx);
  }

  /** Called on entering <code>keyValueIsTransitive</code> rule. */
  @Override
  public void enterKeyValueIsTransitive(KeyValueIsTransitiveContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsTransitive(ctx);
  }

  /** Called on leaving <code>keyValueIsTransitive</code> rule. */
  @Override
  public void exitKeyValueIsTransitive(KeyValueIsTransitiveContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsTransitive(ctx);
  }

  /** Called on entering <code>keyValueIsMetadata</code> rule. */
  @Override
  public void enterKeyValueIsMetadata(KeyValueIsMetadataContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIsMetadata(ctx);
  }

  /** Called on leaving <code>keyValueIsMetadata</code> rule. */
  @Override
  public void exitKeyValueIsMetadata(KeyValueIsMetadataContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIsMetadata(ctx);
  }

  /** Called on entering <code>keyValueInstanceOf</code> rule. */
  @Override
  public void enterKeyValueInstanceOf(KeyValueInstanceOfContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueInstanceOf(ctx);
  }

  /** Called on leaving <code>keyValueInstanceOf</code> rule. */
  @Override
  public void exitKeyValueInstanceOf(KeyValueInstanceOfContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueInstanceOf(ctx);
  }

  /** Called on entering <code>keyValueFormatVersion</code> rule. */
  @Override
  public void enterKeyValueFormatVersion(KeyValueFormatVersionContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueFormatVersion(ctx);
  }

  /** Called on leaving <code>keyValueFormatVersion</code> rule. */
  @Override
  public void exitKeyValueFormatVersion(KeyValueFormatVersionContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueFormatVersion(ctx);
  }

  /** Called on entering <code>keyValueDataVersion</code> rule. */
  @Override
  public void enterKeyValueDataVersion(KeyValueDataVersionContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueDataVersion(ctx);
  }

  /** Called on leaving <code>keyValueDataVersion</code> rule. */
  @Override
  public void exitKeyValueDataVersion(KeyValueDataVersionContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueDataVersion(ctx);
  }

  /** Called on entering <code>keyValueDate</code> rule. */
  @Override
  public void enterKeyValueDate(KeyValueDateContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueDate(ctx);
  }

  /** Called on leaving <code>keyValueDate</code> rule. */
  @Override
  public void exitKeyValueDate(KeyValueDateContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueDate(ctx);
  }

  /** Called on entering <code>keyValueSavedBy</code> rule. */
  @Override
  public void enterKeyValueSavedBy(KeyValueSavedByContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueSavedBy(ctx);
  }

  /** Called on leaving <code>keyValueSavedBy</code> rule. */
  @Override
  public void exitKeyValueSavedBy(KeyValueSavedByContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueSavedBy(ctx);
  }

  /** Called on entering <code>keyValueAutogeneratedBy</code> rule. */
  @Override
  public void enterKeyValueAutogeneratedBy(KeyValueAutogeneratedByContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueAutogeneratedBy(ctx);
  }

  /** Called on leaving <code>keyValueAutogeneratedBy</code> rule. */
  @Override
  public void exitKeyValueAutogeneratedBy(KeyValueAutogeneratedByContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueAutogeneratedBy(ctx);
  }

  /** Called on entering <code>keyValueSubsetdef</code> rule. */
  @Override
  public void enterKeyValueSubsetdef(KeyValueSubsetdefContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueSubsetdef(ctx);
  }

  /** Called on leaving <code>keyValueSubsetdef</code> rule. */
  @Override
  public void exitKeyValueSubsetdef(KeyValueSubsetdefContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueSubsetdef(ctx);
  }

  /** Called on entering <code>keyValueImport</code> rule. */
  @Override
  public void enterKeyValueImport(KeyValueImportContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueImport(ctx);
  }

  /** Called on entering <code>keyValueImport</code> rule. */
  @Override
  public void exitKeyValueImport(KeyValueImportContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueImport(ctx);
  }

  /** Called on entering <code>keyValueSynonymTypedef</code> rule. */
  @Override
  public void enterKeyValueSynonymTypedef(KeyValueSynonymTypedefContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueSynonymTypedef(ctx);
  }

  /** Called on leaving <code>keyValueSynonymTypedef</code> rule. */
  @Override
  public void exitKeyValueSynonymTypedef(KeyValueSynonymTypedefContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueSynonymTypedef(ctx);
  }

  /** Called on entering <code>keyValueRelationshipIdspace</code> rule. */
  @Override
  public void enterKeyValueIdspace(KeyValueIdspaceContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIdspace(ctx);
  }

  /** Called on leaving <code>keyValueDefaultRelationshipIdspace</code> rule. */
  @Override
  public void exitKeyValueIdspace(KeyValueIdspaceContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIdspace(ctx);
  }

  /** Called on entering <code>keyValueDefaultRelationshipIdPrefix</code> rule. */
  @Override
  public void enterKeyValueDefaultRelationshipIdPrefix(
      KeyValueDefaultRelationshipIdPrefixContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueDefaultRelationshipIdPrefix(ctx);
  }

  /** Called on leaving <code>keyValueDefaultRelationshipPrefix</code> rule. */
  @Override
  public void exitKeyValueDefaultRelationshipIdPrefix(
      KeyValueDefaultRelationshipIdPrefixContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueDefaultRelationshipIdPrefix(ctx);
  }

  /** Called on entering <code>keyValueIdMapping</code> rule. */
  @Override
  public void enterKeyValueIdMapping(KeyValueIdMappingContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueIdMapping(ctx);
  }

  /** Called on leaving <code>keyValueIdMapping</code> rule. */
  @Override
  public void exitKeyValueIdMapping(KeyValueIdMappingContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueIdMapping(ctx);
  }

  /** Called on entering <code>keyValueRemark</code> rule. */
  @Override
  public void enterKeyValueRemark(KeyValueRemarkContext ctx) {
    // TODO Auto-generated method stub
    super.enterKeyValueRemark(ctx);
  }

  /** Called on leaving <code>keyValueRemark</code> rule. */
  @Override
  public void exitKeyValueRemark(KeyValueRemarkContext ctx) {
    // TODO Auto-generated method stub
    super.exitKeyValueRemark(ctx);
  }

  /**
   * Called on leaving <code>dbXRefList</code> rule, construct {@link DBXRef} object.
   */
  @Override
  public void exitDbXRefList(DbXRefListContext ctx) {
    final DBXRefList dbXRefList = new DBXRefList();
    for (DbXRefContext xrcCtx : ctx.dbXRef()) {
      dbXRefList.addDBXRef((DBXRef) getValue(xrcCtx));
    }

    setValue(ctx, dbXRefList);
  }

  /**
   * Called on leaving <code>dbXRef</code> rule, construct {@link DBXRef} object.
   */
  @Override
  public void exitDbXRef(DbXRefContext ctx) {
    final String name = ctx.Word().getText();
    final String description = (ctx.QuotedString() == null) ? null : ctx.QuotedString().getText();
    final TrailingModifier trailingModifier = (TrailingModifier) getValue(ctx.trailingModifier());

    setValue(ctx, new DBXRef(name, description, trailingModifier));
  }

  /**
   * Called on leaving <code>trailingModifier</code> rule, construct {@link TrailingModifier}
   * object.
   */
  @Override
  public void exitTrailingModifier(TrailingModifierContext ctx) {
    final TrailingModifier tm = new TrailingModifier();
    for (TrailingModifierKeyValueContext kvCtx : ctx.trailingModifierKeyValue()) {
      tm.addKeyValue(kvCtx.Word(0).getText().trim(), kvCtx.Word(1).getText().trim());
    }

    setValue(ctx, tm);
  }

  /**
   * Convert <code>null</code> and (trimmed) empty string to <code>null</code>.
   * 
   * @param s <code>String</code> to convert
   * @return Trimmed value of <code>s</code> or <code>null</code>.
   */
  private static String trimmedEmptyToNull(String s) {
    if (s == null) {
      return null;
    } else {
      s = s.trim();
      if (s.isEmpty()) {
        return null;
      } else {
        return s.trim();
      }
    }
  }

  /** Overload of {@link #trimmedEmptyToNull(String)} that handles {@link EolComment2Context}. */
  private static String trimmedEmptyToNull(EolComment2Context x) {
    if (x == null || x.Comment2() == null) {
      return null;
    } else {
      final String text = x.Comment2().getText();
      final int pos = text.indexOf('!');
      return trimmedEmptyToNull(text.substring(pos + 1, text.length()).trim());
    }
  }

  /** Overload of {@link #trimmedEmptyToNull(String)} that handles {@link TerminalNode}. */
  private static String trimmedEmptyToNull(TerminalNode n) {
    if (n == null) {
      return null;
    } else {
      return trimmedEmptyToNull(n.getText());
    }
  }

}
