package de.charite.compbio.ontolib.io.obo;

/**
 * Representation of a stanza entry starting with <code>auto-generated-by</code>.
 *
 * @author <a href="mailto:manuel.holtgrewe@bihealth.de">Manuel Holtgrewe</a>
 */
public final class StanzaEntryAutoGeneratedBy extends StanzaEntry {

  /** The generator. */
  private final String generator;

  /**
   * Constructor.
   *
   * @param generator The generator.
   * @param trailingModifier Optional {@link TrailingModifier} of the stanza entry,
   *        <code>null</code> for none.
   * @param comment Optional comment string of the stanza entry, <code>null</code> for none.
   */
  public StanzaEntryAutoGeneratedBy(String generator, TrailingModifier trailingModifier,
      String comment) {
    super(StanzaEntryType.AUTO_GENERATED_BY, trailingModifier, comment);
    this.generator = generator;
  }

  /**
   * @return The generator.
   */
  public String getGenerator() {
    return generator;
  }

  @Override
  public String toString() {
    return "StanzaEntryAutoGeneratedBy [value=" + generator + ", getType()=" + getType()
        + ", getTrailingModifier()=" + getTrailingModifier() + ", getComment()=" + getComment()
        + "]";
  }

}
