name: Deploy to Sonatype Central

on:
  workflow_dispatch:
#  push:
#    tags:
#      - 'v*'  # Trigger the workflow when a tag starting with 'v' is pushed, like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up Maven for Sonatype and deploy to Central
      - name: Deploy to Sonatype Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          echo $SONATYPE_USERNAME;
          echo ${{ secrets.SONATYPE_USERNAME }};
          mvn clean deploy -DskipTests -Prelease \
            -Dusername=${{ secrets.SONATYPE_USERNAME }} \
            -Dpassword=${{ secrets.SONATYPE_PASSWORD }}
